import { Modal, ModalBody, ModalTitle } from "react-bootstrap";

const PrivacyModal = ({
  show,
  onHide,
}: {
  show: boolean;
  onHide: () => void;
}) => {
  return (
    <Modal show={show} onHide={onHide}>
      <Modal.Header closeButton>
        <ModalTitle>Privacy Policy</ModalTitle>
      </Modal.Header>
      <ModalBody>
        <p>
          Welcome to FutureDesk (“Company”, “We”, “our”)! We take your privacy
          very seriously, and we want you to feel secure while using our
          Services. Please carefully read the following Privacy Policy page,
          which governs your use of our Services. Our website located at
          www.FutureDesk.io, our content generation Services accessible through
          app.FutureDesk.io, and any content generated by our content generation
          Services are collectively referred to as “Services”.
        </p>
        <p>
          Agreement to Terms By using our Services, you agree to be bound by our
          Privacy Policy and Terms of Service (“Agreements”). You acknowledge
          that you have read and understood these Agreements. If you do not
          agree with (or cannot comply with) these Agreements, then you may not
          use our Services. These Terms apply to all visitors, users and others
          who wish to access or use our Services.
        </p>
        <p>
          Scope This Privacy Policy applies to personal information processed by
          us on our website, our services offered via the website, and our
          related online and offline offerings.
        </p>
        <p>
          Types of Data We Collect We collect two types of data: Personal Data
          and Usage Data.
        </p>
        <p>
          Personal Data We may ask you to provide us with certain personally
          identifiable information that can be used to contact or identify you
          (“Personal Data”). Personally identifiable information may include,
          but is not limited to Email address, First name and last name
        </p>
        <p>
          Usage Data Usage Data is collected automatically when you use our
          Services. Usage Data may include information such as your
          device&apos;s Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, the
          activities you perform while using our Services, unique device
          identifiers, and other diagnostic data.
        </p>
        <p>
          When you access our Services through a mobile device, we may collect
          certain information automatically, including, but not limited to, the
          type of mobile device you use, your mobile device unique ID, the IP
          address of your mobile device, your mobile operating system, the type
          of mobile internet browser you use, unique device identifiers, and
          other diagnostic data.
        </p>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access our Service through a mobile
          device.
        </p>
        <p>
          Information from 3rd Party Services The Company allows you to create
          an account and log in to use the Service through Google only as of
          now. If you decide to register through or otherwise grant us access to
          a Third-Party Social Media Service, we may collect Personal Data that
          is already associated with your Third-Party Social Media
          Service&apos;s account, such as your name and email address.
        </p>
        <p>
          Session Cookies The Session Cookies are administered by us. These
          Cookies are essential to provide you with services available through
          the Website and to enable you to use some of its features. They help
          to authenticate users and prevent fraudulent use of user accounts.
          Without these Cookies, the services that you have asked for cannot be
          provided, and we only use these Cookies to provide you with those
          services.
        </p>
        <p>
          Use of Your Personal Data We may use Personal Data for the following
          purposes:
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To manage your Account</li>
            <li>To monitor your compliance with our Terms of Service</li>
            <li>To provide customer support</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To detect, prevent, and address technical issues</li>
            <li>
              To provide you with notices about your account and/or
              subscription, including expiration and renewal notices,
              email-instructions, etc.
            </li>
            <li>
              To provide you with news, special offers, and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired
            </li>
            <li>For any other purpose with Your consent </li>
          </ul>
        </p>
        <p>
          Personal Data Retention We will keep your personal data only as long
          as necessary for the purposes stated in this Privacy Policy. We will
          keep and use your personal data only as required to meet legal
          obligations, settle disputes, and enforce agreements and policies.
          Usage data will be kept for a shorter time, except when used to
          enhance security or improve the service.
        </p>
        <p>
          Personal Data Transfer Your information, including personal data, may
          be transferred to and stored on computers located outside your country
          with different data protection laws. By agreeing to this Privacy
          Policy and submitting your information, you consent to the transfer.
          We will take reasonable steps to ensure your data is treated securely
          and in compliance with this Privacy Policy.
        </p>
        <p>
          Disclosure of Personal Data In case of a merger, acquisition or asset
          sale, we may transfer your personal data and will inform you
          beforehand. We may disclose your personal data if required by law,
          valid requests from public authorities, or to protect our rights or
          property.
        </p>
        <p>
          Security of Personal Data While we strive to protect your personal
          data using commercially acceptable methods, no method of transmission
          over the Internet or electronic storage is 100% secure. We cannot
          guarantee absolute security.
        </p>
        <p>
          Data Protection Rights If you are a resident of the European Union,
          you have specific data protection rights covered by GDPR. You may
          contact us to correct, amend, delete or limit your personal data use.
          You have the right to access and withdraw consent to process your
          personal data. You may also file a complaint to a Data Protection
          Authority.
        </p>
        <p>
          Analytics We may use third-party service providers to monitor and
          analyze service use. For example, Google Analytics, which uses data to
          track and report website traffic, may collect and share data with
          Google services.
        </p>
        <p>
          Advertising We may use service providers to show ads to support and
          maintain the service. For example, Google AdSense and DoubleClick
          Cookie may use cookies to serve ads based on user visits. You may
          opt-out of interest-based advertising through Google Ads Settings.
        </p>
        <p>
          Analytics We may use third-party service providers to monitor and
          analyze service use. For example, Google Analytics, which uses data to
          track and report website traffic, may collect and share data with
          Google services.
        </p>
        <p>
          Email Marketing We may use your personal data to contact you with
          newsletters, marketing or promotional materials, and other information
          of interest. You may opt-out of receiving these communications through
          the unsubscribe link or by contacting us.
        </p>
        <p>
          Payments We may use third-party payment processors to process payment
          information for paid products and/or services. We will not store or
          collect payment card details. Payment processors adhere to the PCI-DSS
          requirements for secure payment handling.
        </p>
        <p>
          Links to Other Sites Our service may contain links to third-party
          sites. We have no control over their content, privacy policies, or
          practices. We advise you to review their Privacy Policy before using
          their service.
        </p>
        <p>
          Privacy Policy Changes We may revise this Privacy Policy at any time.
          If there are material changes, we will notify you and require you to
          accept them before continuing to use the service.
        </p>
        <p>
          Contact Us If you have any questions about our Privacy Policy, please
          contact us at contact@FutureDesk.io.
        </p>
      </ModalBody>
    </Modal>
  );
};

export default PrivacyModal;
